import REDUX_DATABASE, {
  getPeopleDatabaseAction,
  getInsurerDatabaseAction,
  getTreatyTypeDatabaseAction,
  getDescriptionDatabseAction,
  getAttachmentsDatabaseAction,
  createPeopleDatabaseAction,
  updatePeopleDatabaseAction,
  deletePeopleDatabaseAction,
  createInsurerDatabaseAction,
  updateInsurerDatabaseAction,
  deleteInsurerDatabaseAction,
  createTreatyTypeDatabaseAction,
  updateTreatyTypeDatabaseAction,
  deleteTreatyTypeDatabaseAction,
  createDescriptionDatabaseAction,
  updateDescriptionDatabaseAction,
  deleteDescriptionDatabaseAction,
  createAttachmentsDatabaseAction,
  updateAttachmentsDatabaseAction,
  deleteAttachmentsDatabaseAction,
  getArticleDatabaseAction,
  createArticleDatabaseAction,
  updateArticleDatabaseAction,
  deleteArticleDatabaseAction,
  clipboardPeopleDatabaseAction,
  insertPeopleDatabaseAction,
} from './actions';

import useAdminDatabase from './useAdminDatabase';

import adminDatabaseSlice from './slice';

export {
  REDUX_DATABASE,
  useAdminDatabase,
  adminDatabaseSlice,
  getPeopleDatabaseAction,
  getInsurerDatabaseAction,
  getTreatyTypeDatabaseAction,
  getDescriptionDatabseAction,
  getAttachmentsDatabaseAction,
  createPeopleDatabaseAction,
  updatePeopleDatabaseAction,
  deletePeopleDatabaseAction,
  createInsurerDatabaseAction,
  updateInsurerDatabaseAction,
  deleteInsurerDatabaseAction,
  createTreatyTypeDatabaseAction,
  updateTreatyTypeDatabaseAction,
  deleteTreatyTypeDatabaseAction,
  createDescriptionDatabaseAction,
  updateDescriptionDatabaseAction,
  deleteDescriptionDatabaseAction,
  createAttachmentsDatabaseAction,
  updateAttachmentsDatabaseAction,
  deleteAttachmentsDatabaseAction,
  getArticleDatabaseAction,
  createArticleDatabaseAction,
  updateArticleDatabaseAction,
  deleteArticleDatabaseAction,
  clipboardPeopleDatabaseAction,
  insertPeopleDatabaseAction,
};
